scrape_configs:
  - job_name: 'MyAppMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['34.168.24.170']
        labels:
          application: 'gametime_RatingUlasan'